server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment-route #路由的id，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 根据服务名称进行路由  lb代表从注册中心获取服务
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment-route2 #路由的id，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 根据服务名称进行路由
          predicates:
            - Path=/payment/lb  #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service #eureka服务端的实例名称
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true #表示是否将自己注册进eureka服务列表内
      fetch-registry: true #表示是否从eureka服务中心获取服务
      defaultZone: http://eureka7001.com:7001/eureka #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址



